<a href="https://colab.research.google.com/github/aicrashcoursewinter24/suthi-lab-01/blob/Lab-2-Sentence-embeddings/gpt_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing the python datasets package

In [2]:
! pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 5.5 MB/s eta 0:00:00


Using the BERT model from the original from the Attention is All You Need paper. Know how to differentiate between lower and uppercase characters

In [3]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizing sentence

In [4]:
encoded = tokenizer.encode("Broken pencils are pointless, but a circles are also pointless.")

In [5]:
print(tokenizer.convert_ids_to_tokens(encoded))

['[CLS]', 'broken', 'pencil', '##s', 'are', 'pointless', ',', 'but', 'a', 'circles', 'are', 'also', 'pointless', '.', '[SEP]']


In [6]:
print(encoded)

[101, 3714, 14745, 2015, 2024, 23100, 1010, 2021, 1037, 7925, 2024, 2036, 23100, 1012, 102]


In [7]:
encoded_input = tokenizer("Peter Piper picked a peck of pickled peppers to pickle his pickle-loving palate.")
print(encoded_input.keys())
print(encoded_input['input_ids'])

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
[101, 2848, 11939, 3856, 1037, 18082, 1997, 4060, 3709, 23582, 2000, 4060, 2571, 2010, 4060, 2571, 1011, 8295, 14412, 3686, 1012, 102]


In [8]:
! pip install sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 910.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 17.1 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=389c5e3d3e7576c3dff6c25efb805f07e036cb1203a7b912678d15d94da10f25
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [9]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')
sentences = [
    "Sally sells seashells by the seashore, swiftly securing slippery shells for seaside strollers.",
    "Walter waited while Wendy weaved whimsical waltzes with Walter's wobbly walrus.",
    "Chester chased a cheetah, challenging his chosen champion to a cheery cheerleading championship."
]
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences,embeddings):
  print("###############################################################\n###############################################################")
  print("")

  print("Sentence:", sentence)
  print("Embedding:", embedding)
  print("")

.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

###############################################################
###############################################################

Sentence: Sally sells seashells by the seashore, swiftly securing slippery shells for seaside strollers.
Embedding: [-3.62235494e-03  4.02172133e-02  4.97602820e-02  9.28536057e-03
 -1.60640609e-02  2.01293696e-02  6.15129508e-02 -1.41682206e-02
 -2.94999722e-02  1.55966347e-02  1.33265816e-02 -7.66085908e-02
  2.93635130e-02  3.77487065e-03  4.07717153e-02  2.61488371e-02
  2.40404885e-02  2.99595818e-02  2.84472313e-02  3.15880217e-02
 -6.71434775e-02  3.26178633e-02  6.20006677e-03  2.56842934e-02
 -7.13892058e-02 -1.74930156e-03  2.67730467e-02 -7.65906721e-02
 -5.40934391e-02 -1.14606367e-02 -7.38636106e-02  3.71508673e-02
 -1.02375466e-02  2.97951549e-02  8.56888890e-02  1.66483745e-02
  7.52810910e-02  1.40698487e-02  1.68053806e-02  5.40850982e-02
 -8.15551952e-02 -5.79907931e-02 -4.40408140e-02 -2.19813511e-02
 -5.39934635e-02 -1.08665094e-01  4.9768

Exploring the vector representation (the "embedding") of any sentence. Looking at teh tokenized form, the list of token_ids integers, or compute cosine similarities between the embeddings

In [10]:
words = ["super","purple", "flower", "drink", "honey"]
single_word_embeddings = model.encode(words)

for word, embed in zip(words, single_word_embeddings):
  print("word: ",word)
  print("embed: ", embed[0:10])
  print("")

word:  super
embed:  [-0.11695115 -0.0248628  -0.05319027  0.03004485 -0.03674866 -0.00230307
  0.0967948   0.03157225 -0.0512606  -0.01352933]

word:  purple
embed:  [-0.05761681 -0.04419539 -0.07217059 -0.03221674 -0.01123551  0.00495188
  0.21028227 -0.03529096  0.04633704 -0.02883166]

word:  flower
embed:  [-0.03122334  0.02821555  0.00795432  0.00980139 -0.0168921   0.04062464
  0.14510563 -0.05703472  0.07084903 -0.03034773]

word:  drink
embed:  [ 0.0007672   0.01072863  0.01950578  0.04526017  0.02661869  0.01924786
  0.11070329 -0.04200888  0.04167427 -0.05632797]

word:  honey
embed:  [-0.04291545 -0.01304961  0.10617466  0.05117056 -0.02791626  0.01674708
  0.09105108  0.03325308  0.06216269  0.0201315 ]



In [11]:
# python code to compute the matrix of cosines between all of the pairs of words in the list above
from sklearn.metrics.pairwise import cosine_similarity
word_embeddings = model.encode(words)
word_similarities = cosine_similarity(word_embeddings)
print(word_similarities)

[[1.0000001  0.37744498 0.20655912 0.23557398 0.3330121 ]
 [0.37744498 0.9999999  0.45274982 0.22169542 0.24307707]
 [0.20655912 0.45274982 1.         0.25971225 0.29151618]
 [0.23557398 0.22169542 0.25971225 1.0000001  0.35337594]
 [0.3330121  0.24307707 0.29151618 0.35337594 1.        ]]


In [12]:
from scipy.spatial.distance import cosine
for key, sentence in enumerate(sentences):
  print(f"Sentence {key+1}: ", sentence)
print("")
print("Cosine similarity between the first two sentences:", cosine(embeddings[0], embeddings[1]))
print("Cosine similarity between the second and third sentences:", cosine(embeddings[1],embeddings[2]))
print("Cosine similarity between the first and third sentences:",cosine(embeddings[0],embeddings[2]))

Sentence 1:  Sally sells seashells by the seashore, swiftly securing slippery shells for seaside strollers.
Sentence 2:  Walter waited while Wendy weaved whimsical waltzes with Walter's wobbly walrus.
Sentence 3:  Chester chased a cheetah, challenging his chosen champion to a cheery cheerleading championship.

Cosine similarity between the first two sentences: 0.8637168258428574
Cosine similarity between the second and third sentences: 0.768151581287384
Cosine similarity between the first and third sentences: 0.9284581691026688


Assignment 1
- Pull in the bert-base-uncased model, use it to generate embeddings for some text, and compare the embeddings to each other via cosine similarity (or euclidean distance)

- Pick a sentence with one or more words with multiple meanings (depending on context), like “flies” (could mean the plural - the insect -  or could be the verb “to fly”), and compute the contextual BERT embeddings for all the the words in the sentence.

- Pick another sentence, with one or more of those ambiguous words but with another meaning, and generate the contextual BERT embeddings for the words in that sentence.  Compare and contrast contextual embedding vectors of words which have changed meaning and those whose meaning has stayed the same.


NB: this code does the embedding for whole sentence instead of individual words.
The next block of code does it rightly.

In [13]:
from scipy.spatial.distance import cosine
from sentence_transformers import SentenceTransformer

# Initialize the model with bert-base-uncased
model = SentenceTransformer('bert-base-uncased')

# Define sentences with words that have multiple meanings
sentence1 = "He cannot bear the weight."
sentence2 = "There is a bear ahead of us."

# Generate embeddings for the sentences
embeddings1 = model.encode([sentence1])
embeddings2 = model.encode([sentence2])

# Extract embeddings for all words in each sentence
words1 = sentence1.split()
words2 = sentence2.split()

embeddings_word1 = {word: model.encode([word])[0] for word in words1}
embeddings_word2 = {word: model.encode([word])[0] for word in words2}

# Compare and contrast contextual embeddings
ambiguous_word = "bear"

print(f"Embedding for the word '{ambiguous_word}' in the sentence '{sentence1}':")
print(embeddings_word1[ambiguous_word])
print("\n")

print(f"Embedding for the word '{ambiguous_word}' in the sentence '{sentence2}':")
print(embeddings_word2[ambiguous_word])
print("\n")

# Compute and print the cosine similarity between the embeddings of the ambiguous word
cos_similarity = 1 - cosine(embeddings_word1[ambiguous_word], embeddings_word2[ambiguous_word])
print(f"Cosine similarity between '{ambiguous_word}' in the two sentences: {cos_similarity}")


.gitattributes:   0%|          | 0.00/491 [00:00<?, ?B/s]

LICENSE:   0%|          | 0.00/11.4k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

(…)kage/Data/com.apple.CoreML/model.mlmodel:   0%|          | 0.00/165k [00:00<?, ?B/s]

weight.bin:   0%|          | 0.00/532M [00:00<?, ?B/s]

(…)sk/float32_model.mlpackage/Manifest.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

model.onnx:   0%|          | 0.00/532M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Embedding for the word 'bear' in the sentence 'He cannot bear the weight.':
[ 8.75118747e-02 -4.09209961e-03 -9.20112357e-02 -5.84967323e-02
 -5.10120876e-02 -1.91835299e-01  3.33695054e-01 -1.19256698e-01
 -1.40636459e-01 -3.15119654e-01 -1.90660760e-01 -2.34459173e-02
  1.02386577e-02 -6.85072690e-03 -4.55642194e-01 -2.26509050e-01
 -1.44945784e-02  6.10246323e-02 -3.26133966e-02  2.66918153e-01
  3.27709019e-01 -1.30187050e-01  1.64120212e-01 -1.83385611e-03
  5.97712137e-02  2.63371319e-01 -1.61420718e-01  1.66432142e-01
 -6.82441369e-02  2.29051307e-01 -1.79748341e-01 -3.01140040e-01
 -5.40056080e-03  2.69855976e-01 -3.84600073e-01 -1.40814528e-01
 -7.39306137e-02  3.24384719e-02 -4.09893036e-01 -2.00770035e-01
 -1.33122802e-02 -2.31610298e-01 -7.82081485e-02 -1.32077485e-01
  1.09314144e-01 -7.21056089e-02 -1.20020367e-01 -1.75433770e-01
 -1.49159893e-01 -5.97945834e-03 -3.43231112e-01  2.55879313e-01
 -1.41652331e-01  9.82408747e-02  4.73195910e-02 -2.49562129e-01
  2.63964683e-

Here is the assignment proper

In [14]:
from scipy.spatial.distance import cosine
from transformers import BertTokenizer, BertModel
import torch

# Initialize the BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def get_embedding(sentence):
    # Tokenize the sentence and convert tokens to token IDs
    inputs = tokenizer(sentence, return_tensors="pt", padding=True, truncation=True)

    # Get the output from the BERT model
    with torch.no_grad():
        outputs = model(**inputs)

    # Extract the embeddings for each token
    embeddings = outputs.last_hidden_state[0].numpy()

    return embeddings

# Define the sentences
sentence1 = "They left to go to the market."
sentence2 = "This is my left hand."

# Get embeddings for tokens in each sentence
embeddings1 = get_embedding(sentence1)
embeddings2 = get_embedding(sentence2)

# Convert the tokens to IDs for both sentences
input_ids1 = tokenizer.encode(sentence1, add_special_tokens=True)
input_ids2 = tokenizer.encode(sentence2, add_special_tokens=True)

# Locate the index of the token "left" in the tokenized sentences
index_left = input_ids1.index(tokenizer.convert_tokens_to_ids("left"))

# Extract embeddings for the token "left" from both sentences using the identified index
embedding_left_1 = embeddings1[index_left]
embedding_left_2 = embeddings2[index_left]

# Compute cosine similarity between the embeddings
cos_similarity = 1 - cosine(embedding_left_1, embedding_left_2)

print(f"Cosine similarity for the token 'like' between the two sentences: {cos_similarity}")


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Cosine similarity for the token 'like' between the two sentences: 0.27476710081100464
